version: "3.8"

services:
  database:
    container_name: tomasdjango_database
    image: postgres
    restart: always
    volumes:
      - ./.pgdata:/var/lib/posgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=pythonpro
      - POSTGRES_USER=pythonpro
    ports:
      - 5434:5432