# Generated by Django 3.2.7 on 2021-10-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('nome', models.CharField(max_length=32)),
                ('slug', models.SlugField(max_length=32)),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
